# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HBShare
  pod 'Weibo_SDK', '~> 3.2.3'
  pod 'WechatOpenSDK', '~> 1.8.0'
  pod 'QQOpenSDK', '~> 3.2.1'

end
